"""empty message

Revision ID: 8a2c813f8d28
Revises: bb7ccc18179d
Create Date: 2024-03-18 16:12:43.058924

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a2c813f8d28'
down_revision = 'bb7ccc18179d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('userid', sa.Integer(), nullable=True))
        batch_op.drop_constraint('comment_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('comment_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['postid'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['userid'], ['id'])
        batch_op.drop_column('post_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userid', sa.Integer(), nullable=True))
        batch_op.drop_constraint('post_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['userid'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('post_ibfk_1', 'user', ['user_id'], ['id'])
        batch_op.drop_column('userid')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comment_ibfk_1', 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key('comment_ibfk_2', 'user', ['user_id'], ['id'])
        batch_op.drop_column('userid')
        batch_op.drop_column('postid')

    # ### end Alembic commands ###
